<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SOHCarModel\SOHCarModel.csproj" />
        <ProjectReference Include="..\SOHDomain\SOHDomain.csproj" />
        <ProjectReference Include="..\SOHMultimodalModel\SOHMultimodalModel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mars.Life.Simulations" Version="4.4.4" />
    </ItemGroup>

</Project>
