<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>
    
    <ItemGroup>
        <Content Include="resources\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Models\KrugerNationalPark\KrugerNationalPark.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mars.Life.Simulations" Version="4.5.4" />
    </ItemGroup>

</Project>
